image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - web/package-lock.json
      prefix: npm
    paths:
      - web/node_modules/
  script:
    - cd web
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - web/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
